### PR TITLE
Add grains exercise

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by tgecho** [comment]
I'm not sure about this one at the moment. I'm pretty fuzzy on integer precision issues, but some numbers in the test suite don't match up with the [canonical data](https://github.com/exercism/x-common/blob/master/exercises/grains/canonical-data.json) (64 and total).

This seems to be a fundamental problem with these numbers being over `Number.MAX_SAFE_INTEGER` (9007199254740991). This elm compiler issue might also be relevant https://github.com/elm-lang/elm-compiler/issues/1246

So I dunno... is just going with what Elm/JS can represent kosher enough for our purposes?

**Comment by ErikSchierboom** [comment]
@tgecho I think so. I also struggled with while creating the exercise. Let's just remove the two tests that cannot be correctly represented. I'll update the PR later.

**Comment by ErikSchierboom** [comment]
@tgecho I've updated the PR!

**Comment by ErikSchierboom** [comment]
@tgecho The PR has been updated!

**Comment by tgecho** [comment]
I'd really love to get this merged, but the overflowing test cases are still in there (as an aside: I thought I'd once seen an elm-bigint library, but I guess I was mistaken).

For the sake of moving on, what if you add a comment next to those test cases explaining what the value *should* be and a link to a reasonable explanation of overflow issues (and maybe that compiler issue?). I'm just uncomfortable with leaving the wrong numbers in with no explanation.

Also the exercise format changed a bit with the update for elm 0.18, so there are a few updates for that (see the diffs in https://github.com/exercism/xelm/pull/126 for reference).

Thanks!

**Comment by ErikSchierboom** [comment]
@tgecho That's odd, I must have made a mistake. I'll remove the overflows, I think that's the best option. I'll also update to 0.18.

**Comment by ErikSchierboom** [comment]
@tgecho The PR has been updated to 0.18 and the new exercise format. It also doesn't contain the overflow anymore.

**Comment by tgecho** [comment]
Just updated this branch for elm-test 0.18.3 compatibility and merged it over at https://github.com/exercism/xelm/pull/142. Thanks, and sorry for the delay!

**Comment by ErikSchierboom** [comment]
Cool! No problem

**Pull request closed without merging**
