### PR TITLE
Fix Tests

### PR DESCRIPTION
**Pull request by jehoshua02**
Fixes https://github.com/exercism/xelm/issues/100

+ Upgrade to node-test-runner 2
+ Lock down elm and elm-test versions, document it
+ Prevent elm-test from installing in each directory to reduce ci run time
+ Don't cache elm-stuff in ci because it causes probs

### CODE REVIEW

**Comment by jehoshua02** [comment]
Close but no cigar. Passed locally but still failed on Travis for a different reason.

**Comment by jehoshua02** [comment]
Well, it passed falsely.

**Comment by jehoshua02** [comment]
```
-------------------------------------------------------
Testing Accumulate
Success! Compiled 13 modules.
elm-make: elm-stuff/build-artifacts/0.17.1/rtfeldman/node-test-runner/2.0.0/Test-Runner-Node-App.elmo: openFile: does not exist (No such file or directory)
Compilation failed for exercises/accumulate/AccumulateTests.elm
```

Travis says it passes, but it actually didn't. Need to fix that.

**Comment by jehoshua02** [comment]
@tgecho oh, Travis is failing because it's trying to run master instead of my branch, even though my pull request triggered the build:

```
git clone --depth=50 https://github.com/exercism/xelm.git exercism/xelm
```

Passes locally though 😄 👍

**Comment by jehoshua02** [comment]
nevermind, it is checking out the branch (I think) the output in Travis was collapsed:

```
$ cd exercism/xelm
0.34s$ git fetch origin +refs/pull/107/merge:
remote: Counting objects: 78, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 78 (delta 67), reused 75 (delta 65), pack-reused 0
Unpacking objects: 100% (78/78), done.
From https://github.com/exercism/xelm
 * branch            refs/pull/107/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
```

But I am unable to reproduce the errors locally.

**Comment by jehoshua02** [comment]
Okay, looks like tests might pass as long as they complete soon enough. Then we can review, clean up, and I think it's good to go.

**Comment by tgecho** [comment]
Nice work! The caching issue was actually a travis/elm thing we've been wrestling with. I think it's the same thing that can cause elm builds to get a bit hosed locally. I cleared the cache and reran the commit and it seems fine without disabling the cache. Squash merged here: https://github.com/exercism/xelm/pull/106

Thanks! 🎉

**Pull request closed without merging**
