### PR TITLE
adds roman numerals exercise

### PR DESCRIPTION
**Pull request by rebelwarrior**
I did my hand at adding an exercise. Here is the Roman Numerals one, the example is based on the Elixir one.

### CODE REVIEW

**Comment by tgecho** [comment]
Awesome! The test and example look good to me.

To actually activate the exercise, you'll need to add an entry to the `config.json`. To allow the Travis CI job to run it, you'll also need to add it to the `elm-package.json`.

Thanks!

**Comment by rebelwarrior** [comment]
Ok will do. (As soon as I figure out how). :)

**Comment by rebelwarrior** [comment]
OK I'm going to close this pull request and do those things and make another.

**Comment by tgecho** [comment]
For future reference, you don't need to open a new PR... just push (even force push) to your branch and the PR will update automatically!

**Comment by kytrinyx** [comment]
Another thing—this page might be helpful: http://exercism.io/languages/elm/contribute (and if it's confusing, please holler so we can improve it). Notice in particular the canonical test data icon... if a problem has that, it's easier to convert it.

**Pull request closed without merging**
