### PR TITLE
Pin elm-console to 1.1.0 to fix a build failure introduced in 1.1.1

### PR DESCRIPTION
**Pull request by tgecho**

### CODE REVIEW

**Comment by tgecho** [comment]
Well that's maddening. I seriously upgraded locally and everything broke. I then downgraded and it started working again. Poking a bit more...

**Comment by tgecho** [comment]
So, this PR doesn't really seem to do anything. I reset the Travis cache (under settings) and now it seems to be passing :(

image

**Comment by parkerl** [comment]
Huh. Irritating. Merge?

**Comment by kytrinyx** [comment]
I'm confused--it started working again without pinning the build?

**Comment by tgecho** [comment]
Nope. I cleared travis' build cache and it cleared up. I'm not sure if the issue is with Travis, elm-package or something we're doing. This PR seems to be a dead end. If this happens again I'll try to find some time to pin it down a little better.

**Comment by kytrinyx** [comment]
Awesome, thanks for digging into it.

**Pull request closed without merging**
