### PR TITLE
Docs and test workflow

### PR DESCRIPTION
**Pull request by tgecho**
As proposed in https://github.com/exercism/xelm/issues/23, I copied the `elm-package.json` file to each exercise directory and updated the docs to reflect this change.

I also adapted the TESTS.md from the exercism/xgo repo. I'm going to throw something in ABOUT/LEARNING/RESOURCES docs as well, but I wanted to get this up for your perusal @parkerl

### CODE REVIEW

**Comment by tgecho** [comment]
Eh... fixing up the travis test...

**Comment by tgecho** [comment]
Turns out it takes a lot longer to run through the CI tests with this elm-package.json per exercise scheme (~20min vs 5-7!). I put the root elm-package.json file back and reverted my changes to build.sh. It'll mean needing to add the slug/path to both the config.json and root elm-package.json, but only as a one time thing.

**Comment by tgecho** [comment]
@parkerl I think this should be good to go now. If this approach works for you, I'll update and PR all of the exercises I have queued up.

**Comment by parkerl** [comment]
Thanks @tgecho! I want to give these changes a good look which I haven't had time for yet, but looks great at first glance.

**Comment by tgecho** [comment]
Sounds good!

**Pull request merged**
