### PR TITLE
When we're ready: activate the track!

### PR DESCRIPTION
**Pull request by tgecho**

### CODE REVIEW

**Comment by parkerl** [comment]
@tgecho can you fix the conflicts on this so we can take this thing live?

**Comment by kytrinyx** [comment]
w00t. OK, @tgecho I think we're ready. Want to rebase this onto master?

**Comment by kytrinyx** [comment]
haha. Ditto. What he said.

**Comment by tgecho** [comment]
Well... that's not quite the silliest merge conflict I've ever seen. Fixed!

**Comment by parkerl** [comment]
:tada: w00t!!!!!!

**Comment by kytrinyx** [comment]
Yay! Updating and deploying the api now!

**Pull request merged**
