### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by tgecho**
Combines the test updates by @jehoshua02 with a few more config updates

### CODE REVIEW

**Comment by jehoshua02** [comment]
@tgecho Pass! (still waiting for Travis though lol)

**Comment by jehoshua02** [comment]
Bummer.

```
Your test run exceeded 120 minutes. 
One possible solution is to split up your test run.
```

**Comment by tgecho** [comment]
That's crazy. I don't know why it's installing elm stuff for every test.

**Comment by jehoshua02** [comment]
@tgecho :eyes: https://github.com/exercism/xelm/commit/54e30178#diff-d296a94261ea80f5a08b1cb3f93fb777

**Comment by jehoshua02** [comment]
@tgecho ah, but I don't see where it changes directory though. Maybe `elm-test` does it automagically?

**Comment by jehoshua02** [comment]
Yep

```
~/exercism/elm/largest-series-product
$ rm -fr elm-stuff/
~/exercism/elm/largest-series-product
$ cd ..
~/exercism/elm
$ elm-test largest-series-product/LargestSeriesProductTests.elm 
Starting downloads...

  ● elm-community/shrink 1.1.0
  ● elm-community/elm-lazy-list 1.2.0
  ● elm-community/json-extra 1.0.0
  ● elm-community/elm-test 2.0.1
  ● elm-lang/lazy 1.0.0
  ● mgold/elm-random-pcg 3.0.1
  ● elm-lang/core 4.0.5
  ● elm-lang/html 1.1.0
  ● rtfeldman/node-test-runner 2.0.0
  
● elm-lang/virtual-dom 1.1.0
Packages configured successfully!
Success! Compiled 49 modules.                                       
Successfully generated /var/folders/1p/qm72h6016651chtkxqygy7_w0000gn/T/elm_test_116722-59182-grfqr5.xhrbai3sor.js

elm-test
--------

Running 17 tests. To reproduce these results, run: elm-test --seed 744828153


TEST RUN PASSED

Duration: 36 ms
Passed:   17
Failed:   0

```

**Comment by jehoshua02** [comment]
@tgecho elm-test seems to scan up the directory tree from the file you are trying to run and installs in any directory it finds an elm-package.json. In build.sh, try deleting elm-package.json before running test.

**Comment by tgecho** [comment]
That's a bummer. I won't be able to dig into this until the evening, but you're welcome to try another PR with tweaks. I'd love to not need to delete stuff in mid build, but it might be worth doing as a quick test to make sure it at least passes.

**Comment by jehoshua02** [comment]
Okay, I'm giving it a try: https://github.com/exercism/xelm/pull/107

**Pull request merged**
