### PR TITLE
Add allergies exercise

### PR DESCRIPTION
**Pull request by tgecho**
I'm not sure how I feel about this exercise, but I'm young enough that rampant bitwise stuff was never really a part of my background, so that colors my view a bit. :)

### CODE REVIEW

**Comment by parkerl** [comment]
Sorry I haven't had a chance to review these in detail. I am on spring break.  I will try to get to them in the next few days.

**Comment by tgecho** [comment]
No worries. Enjoy your time away!

**Comment by parkerl** [comment]
This looks good. Wondering if there are a couple more tests you could add? Some scores that are beyond the sum of all the allergies?

**Comment by tgecho** [comment]
Sure! I added a few other "ignore parts" tests.

**Comment by parkerl** [comment]
Great! :tada:

**Pull request merged**
