### PR TITLE
Remove test_pattern: “TODO” from config.json (should fix #48)

### LINKED ISSUE #48: Test suites aren't showing up on exercism.io
The exercise pages have a "Test Suite" tab, but it seems to be broken for the Elm exercises.

For example...
The Python test suite: http://exercism.io/exercises/python/hello-world
The Elm version is broken: http://exercism.io/exercises/elm/hello-world

Is there something we can/should tweak to fix this?

### PR DESCRIPTION
**Pull request by tgecho**

### CODE REVIEW

**Comment by parkerl** [comment]
@tgecho what happened to the build?

**Comment by tgecho** [comment]
Yikes! I don't know. Works on my machine. I triggered another build attempt.

**Comment by tgecho** [comment]
It looks like something unrelated to these PRs has broken (I restarted #46 and it's failing too). Maybe a dependency? I think we pretty much pinned the versions of everything.

**Comment by parkerl** [comment]
Damn. Do you have time to dig in to it? I can in the AM.

**Comment by tgecho** [comment]
Looks like the elm-console bump to 1.1.1 busted things: https://github.com/laszlopandy/elm-console/commit/d788cac07894069370f97ab2cbe2211b653b131e

Working on a downgrade PR.

**Comment by tgecho** [comment]
Well, now that we've apparently cleared up that little distraction, this rather innocuous PR should be good to merge :)

**Pull request merged**
