### PR TITLE
Add list-ops exercise

### PR DESCRIPTION
**Pull request by jcshih**
I'm unsure about adding large list tests, as elm doesn't have TCO, and it isn't really elm's intention to do large computations. Thoughts?

### CODE REVIEW

**Comment by tgecho** [comment]
This is great! My only hesitation about just merging is this issue: https://github.com/exercism/x-common/issues/129

Accumulate and strain both kind of duplicate a subset of this test, and it looks like a rename from `list-ops` to `sequence-ops` is on the table. I think we can probably merge anyway, but I'd like let it sit for a day or so.

**Comment by jcshih** [comment]
Thanks! No problem. I don't really understand the exact relationship of the same exercise across languages, so I defer to you and others on this decision.

**Comment by kytrinyx** [comment]
Problem descriptions / metadata are language-independent. Then any of the languages on Exercism can add their own implementation (test suite + reference solution). The README for the exercise is a combination of language-independent data and language/implementation specific hints.

**Comment by tgecho** [comment]
Thanks @jcshih 🎉

**Pull request merged**
